export const arr = [
  // Procedural
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Hurdles Two Step",
      workout_exercise_video: "https://www.youtube.com/embed/YlFDFxbIKX4",
      setNumber: 1,
      totalSets: 2,
      groupName: "Proc",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "0",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "0", restTime: 5, setNumber: 1, id: 300 },
  },
  {
    type: "REST",
    data: {},
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Hurdles Two Step",
      workout_exercise_video: "https://www.youtube.com/embed/YlFDFxbIKX4",
      setNumber: 2,
      totalSets: 2,
      groupName: "Proc",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "0",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "0", restTime: 5, setNumber: 2, id: 300 },
  },
  {
    type: "REST",
    data: {},
  },
  //   Super Set
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Ice Skating",
      workout_exercise_video: "https://www.youtube.com/embed/ifIDQ8wQ67Q",
      setNumber: 1,
      totalSets: 2,
      groupName: "Super",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "1", restTime: 0, id: 300, setNumber: 1 },
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Child Pose",
      workout_exercise_video: "https://www.youtube.com/embed/i1FtV2aduMY",
      setNumber: 1,
      totalSets: 2,
      groupName: "Super",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "1", restTime: 0, id: 300, setNumber: 1 },
  },
  {
    type: "REST",
    data: {},
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Ice Skating",
      workout_exercise_video: "https://www.youtube.com/embed/ifIDQ8wQ67Q",
      setNumber: 2,
      totalSets: 2,
      groupName: "Super",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "1", restTime: 0, id: 300, setNumber: 2 },
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Child Pose",
      workout_exercise_video: "https://www.youtube.com/embed/i1FtV2aduMY",
      setNumber: 2,
      totalSets: 2,
      groupName: "Super",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "1", restTime: 0, id: 300, setNumber: 2 },
  },
  {
    type: "REST",
    data: {},
  },
  //   Tri Set
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Ladder Lateral Shuffle",
      workout_exercise_video:
        "https://www.youtube.com/embed/x6cSoxXu8cc?controls=0",
      setNumber: 1,
      totalSets: 2,
      groupName: "Tris",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "1", restTime: 0, id: 300, setNumber: 1 },
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Zig Zag 2",
      workout_exercise_video: "https://www.youtube.com/embed/W5Y0fR5iM_Y",
      setNumber: 1,
      totalSets: 2,
      groupName: "Tris",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "1", restTime: 0, id: 300, setNumber: 1 },
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Lax Ball Rolling Upper Back Roll",
      workout_exercise_video:
        "https://www.youtube.com/embed/JwBEVaX96NY?controls=0",
      setNumber: 1,
      totalSets: 2,
      groupName: "Tris",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "1", restTime: 0, id: 300, setNumber: 1 },
  },
  {
    type: "REST",
    data: {},
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Ladder Lateral Shuffle",
      workout_exercise_video:
        "https://www.youtube.com/embed/x6cSoxXu8cc?controls=0",
      setNumber: 2,
      totalSets: 2,
      groupName: "Tris",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "1", restTime: 0, id: 300, setNumber: 2 },
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Zig Zag 2",
      workout_exercise_video: "https://www.youtube.com/embed/W5Y0fR5iM_Y",
      setNumber: 2,
      totalSets: 2,
      groupName: "Tris",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "1", restTime: 0, id: 300, setNumber: 2 },
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Lax Ball Rolling Upper Back Roll",
      workout_exercise_video:
        "https://www.youtube.com/embed/JwBEVaX96NY?controls=0",
      setNumber: 2,
      totalSets: 2,
      groupName: "Tris",
      groupType: "Circuit",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "1", restTime: 0, id: 300, setNumber: 2 },
  },
  {
    type: "REST",
    data: {},
  },
  //   Quarter Set
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Ladder Single Leg In Out Side Hops",
      workout_exercise_video:
        "https://www.youtube.com/embed/0PgJ9iUnWxc?controls=0",
      setNumber: 1,
      totalSets: 1,
      groupName: "Quarter",
      groupType: "Strength",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "0", restTime: 2, id: 300, setNumber: 1 },
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Ladder Single Leg Hop",
      workout_exercise_video:
        "https://www.youtube.com/embed/5lsdUf23YOk?controls=0",
      setNumber: 1,
      totalSets: 1,
      groupName: "Quarter",
      groupType: "Strength",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "0", restTime: 2, id: 300, setNumber: 1 },
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Bike",
      workout_exercise_video: "https://www.youtube.com/embed/I44PRdefD84",
      setNumber: 1,
      totalSets: 1,
      groupName: "Quarter",
      groupType: "Strength",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "0", restTime: 2, id: 300, setNumber: 1 },
  },
  {
    type: "EXERCISE",
    data: {
      workout_exercise_name: "Windmill",
      workout_exercise_video: "https://www.youtube.com/embed/5MI-cpHDzQI",
      setNumber: 1,
      totalSets: 1,
      groupName: "Quarter",
      groupType: "Strength",
      workout_load: "3",
      workout_repetition_type: "Seconds",
      workout_reps: "2",
      workout_reps_each_side: "1",
    },
  },
  {
    type: "INPUT",
    data: { workout_load_required: "0", restTime: 2, id: 300, setNumber: 1 },
  },
  {
    type: "REST",
    data: {},
  },
];
