[
  {
    id: 195,
    group_name: "Proc",
    group_set_type: "Procedural",
    group_sets: "0",
    group_rest: "0",
    workout_type: "Circuit",
    workout_group_exercise: [
      {
        id: 300,
        workout_exercise: "164",
        workout_exercise_name: "Hurdles Two Step",
        workout_reps: "2",
        workout_load: "3",
        workout_load_required: "0",
        workout_reps_each_side: "0",
        workout_repetition_type: "Seconds",
        workout_sets: "2",
        workout_rest: "3",
        workout_exercise_video: "https://www.youtube.com/embed/YlFDFxbIKX4",
        workout_exercise_description: null,
        exercise_complete_details: [
          {
            id: 133,
            annual_training_program_exercise_set_number: "1",
            annual_training_program_reps_completed: "0",
            annual_training_program_load_completed: "0",
          },
          {
            id: 134,
            annual_training_program_exercise_set_number: "2",
            annual_training_program_reps_completed: "0",
            annual_training_program_load_completed: "0",
          },
          {
            id: 144,
            annual_training_program_exercise_set_number: "3",
            annual_training_program_reps_completed: "0",
            annual_training_program_load_completed: "0",
          },
        ],
      },
    ],
  },
  {
    id: 196,
    group_name: "Super",
    group_set_type: "Super Set",
    group_sets: "2",
    group_rest: "3",
    workout_type: "Circuit",
    workout_group_exercise: [
      {
        id: 305,
        workout_exercise: "213",
        workout_exercise_name: "Ice Skating",
        workout_reps: "2",
        workout_load: "3",
        workout_load_required: "1",
        workout_reps_each_side: "1",
        workout_repetition_type: "Seconds",
        workout_sets: "2",
        workout_rest: "3",
        workout_exercise_video: "https://www.youtube.com/embed/ifIDQ8wQ67Q",
        workout_exercise_description: null,
        exercise_complete_details: [
          {
            id: 142,
            annual_training_program_exercise_set_number: "1",
            annual_training_program_reps_completed: "0",
            annual_training_program_load_completed: "0",
          },
          {
            id: 143,
            annual_training_program_exercise_set_number: "2",
            annual_training_program_reps_completed: "0",
            annual_training_program_load_completed: "0",
          },
        ],
      },
      {
        id: 306,
        workout_exercise: "182",
        workout_exercise_name: "Child Pose",
        workout_reps: "3",
        workout_load: "4",
        workout_load_required: "1",
        workout_reps_each_side: "1",
        workout_repetition_type: "Seconds",
        workout_sets: "2",
        workout_rest: "3",
        workout_exercise_video: "https://www.youtube.com/embed/i1FtV2aduMY",
        workout_exercise_description: null,
        exercise_complete_details: [],
      },
    ],
  },
  {
    id: 197,
    group_name: "Tris",
    group_set_type: "Triset",
    group_sets: "2",
    group_rest: "3",
    workout_type: "Circuit",
    workout_group_exercise: [
      {
        id: 292,
        workout_exercise: "169",
        workout_exercise_name: "Ladder Lateral Shuffle",
        workout_reps: "2",
        workout_load: "2",
        workout_load_required: "0",
        workout_reps_each_side: "0",
        workout_repetition_type: "Seconds",
        workout_sets: "2",
        workout_rest: "3",
        workout_exercise_video:
          "https://www.youtube.com/embed/x6cSoxXu8cc?controls=0",
        workout_exercise_description: null,
        exercise_complete_details: [
          {
            id: 137,
            annual_training_program_exercise_set_number: "1",
            annual_training_program_reps_completed: "0",
            annual_training_program_load_completed: "0",
          },
          {
            id: 138,
            annual_training_program_exercise_set_number: "2",
            annual_training_program_reps_completed: "0",
            annual_training_program_load_completed: "0",
          },
        ],
      },
      {
        id: 293,
        workout_exercise: "276",
        workout_exercise_name: "Zig Zag 2",
        workout_reps: "2",
        workout_load: "2",
        workout_load_required: "1",
        workout_reps_each_side: "1",
        workout_repetition_type: "Seconds",
        workout_sets: "2",
        workout_rest: "3",
        workout_exercise_video: "https://www.youtube.com/embed/W5Y0fR5iM_Y",
        workout_exercise_description: null,
        exercise_complete_details: [],
      },
      {
        id: 294,
        workout_exercise: "178",
        workout_exercise_name: "Lax Ball Rolling Upper Back Roll",
        workout_reps: "1",
        workout_load: "2",
        workout_load_required: "1",
        workout_reps_each_side: "1",
        workout_repetition_type: "Seconds",
        workout_sets: "2",
        workout_rest: "3",
        workout_exercise_video:
          "https://www.youtube.com/embed/JwBEVaX96NY?controls=0",
        workout_exercise_description: null,
        exercise_complete_details: [],
      },
    ],
  },
  {
    id: 198,
    group_name: "Quart",
    group_set_type: "Quarter Set",
    group_sets: "3",
    group_rest: "4",
    workout_type: "Circuit",
    workout_group_exercise: [
      {
        id: 295,
        workout_exercise: "171",
        workout_exercise_name: "Ladder Single Leg In Out Side Hops",
        workout_reps: "2",
        workout_load: "3",
        workout_load_required: "0",
        workout_reps_each_side: "0",
        workout_repetition_type: "Seconds",
        workout_sets: "3",
        workout_rest: "4",
        workout_exercise_video:
          "https://www.youtube.com/embed/0PgJ9iUnWxc?controls=0",
        workout_exercise_description: null,
        exercise_complete_details: [
          {
            id: 139,
            annual_training_program_exercise_set_number: "1",
            annual_training_program_reps_completed: "0",
            annual_training_program_load_completed: "0",
          },
          {
            id: 140,
            annual_training_program_exercise_set_number: "2",
            annual_training_program_reps_completed: "0",
            annual_training_program_load_completed: "0",
          },
          {
            id: 141,
            annual_training_program_exercise_set_number: "3",
            annual_training_program_reps_completed: "0",
            annual_training_program_load_completed: "0",
          },
        ],
      },
      {
        id: 296,
        workout_exercise: "170",
        workout_exercise_name: "Ladder Single Leg Hop",
        workout_reps: "3",
        workout_load: "3",
        workout_load_required: "0",
        workout_reps_each_side: "0",
        workout_repetition_type: "Seconds",
        workout_sets: "3",
        workout_rest: "4",
        workout_exercise_video:
          "https://www.youtube.com/embed/5lsdUf23YOk?controls=0",
        workout_exercise_description: null,
        exercise_complete_details: [],
      },
      {
        id: 297,
        workout_exercise: "108",
        workout_exercise_name: "Bike",
        workout_reps: "2",
        workout_load: "3",
        workout_load_required: "0",
        workout_reps_each_side: "0",
        workout_repetition_type: "Seconds",
        workout_sets: "3",
        workout_rest: "4",
        workout_exercise_video: "https://www.youtube.com/embed/I44PRdefD84",
        workout_exercise_description: null,
        exercise_complete_details: [],
      },
      {
        id: 298,
        workout_exercise: "258",
        workout_exercise_name: "Windmill",
        workout_reps: "3",
        workout_load: "3",
        workout_load_required: "0",
        workout_reps_each_side: "0",
        workout_repetition_type: "Seconds",
        workout_sets: "3",
        workout_rest: "4",
        workout_exercise_video: "https://www.youtube.com/embed/5MI-cpHDzQI",
        workout_exercise_description: null,
        exercise_complete_details: [],
      },
    ],
  },
];
