import { StyleSheet } from "react-native";
import { Colors } from "../../../../constants/Colors";
import {
  DEV_HEIGHT,
  DEV_WIDTH,
  IS_IOS,
} from "../../../../constants/DeviceDetails";
import {
  ROBO_MEDIUM,
  ROBO_ITALIC,
  ROBO_REGULAR,
  ROBO_BOLD,
  POP_MEDIUM,
  POP_REGULAR,
} from "../../../../constants/Fonts";
import { findHeight, findSize, FLEX_WIDTH } from "../../../../utils/helper";

export const styles = StyleSheet.create({
  heads: {
    fontSize: 15,
    color: Colors.WHITE_COLOR,
    fontFamily: POP_MEDIUM,
    marginVertical: 5,
  },
  scaleBtn: {
    height: findSize(29),
    width: findSize(29),
    backgroundColor: Colors.BACKGROUND,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: findSize(15),
  },
  scaleBtn1: {
    height: findSize(33),
    width: findSize(65),
    backgroundColor: Colors.BACKGROUND,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: findSize(16),
  },
  scaleTxt: {
    color: Colors.WHITE_COLOR,
    fontFamily: POP_REGULAR,
    fontSize: 13,
  },
  intensityContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 5,
  },
  intensityLevel: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginBottom: 5,
  },
  intensityName: {
    fontFamily: POP_REGULAR,
    marginBottom: 1,
    color: Colors.WHITE_COLOR,
  },
  submitBtn: {
    width: 130,
    alignSelf: "center",
    backgroundColor: Colors.GREEN_COLOR,
    marginVertical: 15,
    height: 38,
  },
  outerBox: {
    borderWidth: 1,
    padding: 15,
    borderColor: Colors.LIGHT_GREY,
  },
  workComplete: {
    textAlign: "center",
    fontSize: 30,
    fontFamily: ROBO_MEDIUM,
  },
  workCompleteRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
  line: {
    borderBottomWidth: 1,
    borderBottomColor: "#C0C0C0",
    marginVertical: 5,
  },
  tableRow: {
    fontSize: 15,
    color: Colors.BLACK_COLOR,
    fontFamily: ROBO_REGULAR,
    width: 73,
  },
  exerciseAndType: {
    fontSize: findSize(16),
    fontFamily: POP_REGULAR,
    textAlign: "center",

    marginVertical: 10,
    color: Colors.WHITE_COLOR,
  },
  groupExercise: {
    fontSize: findSize(17),
    fontFamily: POP_MEDIUM,
    textAlign: "center",
    marginBottom: 15,
    color: Colors.WHITE_COLOR,
  },
  headRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 7,
    marginBottom: 10,
  },
  webView: {
    height: DEV_WIDTH > DEV_HEIGHT ? DEV_HEIGHT * 0.5 : DEV_HEIGHT * 0.3,
    width: DEV_WIDTH - 40,
    backgroundColor: Colors.BG_LIGHT,
    alignSelf: "center",
  },
  nextBtn: {
    backgroundColor: Colors.LIGHT_GREY,
    borderColor: Colors.LIGHT_GREY,
    borderWidth: 1,
    marginVertical: 15,
    height: 38,
    width: 85,
    alignSelf: "center",
    color: Colors.WHITE_COLOR,
  },
  timerTxt: {
    fontSize: findSize(40),
    color: Colors.WHITE_COLOR,
    fontFamily: POP_MEDIUM,
    textAlign: "center",
  },
  wellInfo: {
    fontSize: 28,
    color: Colors.BLACK_COLOR,
    fontFamily: ROBO_BOLD,
    textAlign: "center",
  },
  percent: {
    fontSize: 17,
    color: Colors.WHITE_COLOR,
    fontFamily: POP_REGULAR,
  },
  accomplish: {
    fontSize: 30,
    textAlign: "center",
    fontFamily: ROBO_BOLD,
    marginVertical: 10,
  },
  wellBg: {
    width: 55,
    backgroundColor: Colors.BLACK_COLOR,
    alignItems: "center",
    justifyContent: "center",
    height: 30,
  },
  wellTxt: {
    color: Colors.WHITE_COLOR,
    fontSize: 17,
    fontFamily: ROBO_REGULAR,
  },
  wellRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  wellTxtRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 7,
  },
  accompRow: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  circularRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  clearBtnTxt: {
    color: Colors.SKY_COLOR,
    textDecorationLine: "underline",
    fontFamily: ROBO_MEDIUM,
    fontSize: 14,
  },
  selectedMuscle: {
    fontSize: findSize(28),
    color: Colors.WHITE_COLOR,
    fontFamily: POP_REGULAR,
  },
  selctedMuscleContainer: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
  },
  clearBtn: {
    marginBottom: 7,
    alignSelf: "flex-end",
  },
  completeWorkout: {
    // fontFamily: ROBO_ITALIC,
    fontSize: 14,
    // textDecorationLine: 'underline',

    color: Colors.WHITE_COLOR,
  },
  completeWorkBtn: {
    // marginTop: 10,
    alignSelf: "flex-end",
    marginBottom: 15,
    backgroundColor: Colors.SKY_COLOR,
    paddingHorizontal: 20,
    // paddingVertical: 8,
    borderColor: Colors.LIGHT_GREY,
    borderWidth: 1,
    borderRadius: 10,
    width: 95,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  exerciseType: {
    textAlign: "center",
    fontFamily: ROBO_REGULAR,
    fontSize: 16,
    marginVertical: 10,
  },
  nextPress: {
    backgroundColor: Colors.LIGHT_GREY,
    borderColor: Colors.LIGHT_GREY,
    borderWidth: 1,
    height: 38,
    width: 85,
    alignSelf: "center",
    marginTop: IS_IOS ? 0 : 10,
  },
  preExercisesContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  followingSelected: {
    fontSize: findSize(15),
    color: Colors.WHITE_COLOR,
    fontFamily: POP_REGULAR,
    marginVertical: 10,
    textAlign: "center",
  },
  chooseBelowTxt: {
    fontSize: findSize(15),
    color: Colors.WHITE_COLOR,
    fontFamily: POP_REGULAR,
    marginBottom: 10,
    textAlign: "center",
    paddingBottom: 10,
  },
  deloadTxt: {
    fontSize: 25,
    color: Colors.BG_LIGHT,
    fontFamily: ROBO_BOLD,
    textAlign: "center",
    marginBottom: 10,
  },
  tabsContainerStyle: {
    height: findHeight(50),
    borderWidth: 0,
    backgroundColor: Colors.VALHALLA,

    borderRadius: findHeight(26),
    width: 130,
    justifyContent: "center",
    alignItems: "center",
  },
  tabStyle: {
    backgroundColor: Colors.WHITE_COLOR,
    borderColor: Colors.WHITE_COLOR,
    borderWidth: 1,

    marginHorizontal: 1,
  },
  tabTextStyle: {
    color: Colors.BG_LIGHT,
    fontFamily: ROBO_REGULAR,
    fontSize: 14,
  },
  activeTabStyle: {
    backgroundColor: Colors.GREEN_COLOR,
    // borderTopEndRadius: 10,
    // borderBottomEndRadius: 10,
    borderColor: Colors.GREEN_COLOR,
    borderWidth: 1,
    elevation: 2,
    marginHorizontal: 1,
  },
  activeTabTextStyle: {
    color: Colors.WHITE_COLOR,
    fontSize: 16,
    fontFamily: ROBO_MEDIUM,
  },
  setTotal: {
    color: Colors.WHITE_COLOR,
    fontFamily: POP_REGULAR,
    fontSize: findSize(11),
  },
  setNo: {
    color: Colors.ORANGE,
    fontSize: findSize(11),
    fontFamily: POP_REGULAR,
    textAlign: "right",
    lineHeight: findSize(12),
  },
  load: {
    color: Colors.INPUT_PLACE,
    fontSize: findSize(11),
    fontFamily: POP_REGULAR,
  },
  reps: {
    color: Colors.WHITE_COLOR,
    fontSize: findSize(11),
    fontFamily: POP_REGULAR,
    lineHeight: findSize(12),
  },
  setTile: {
    backgroundColor: Colors.VALHALLA,
    borderRadius: findSize(7),
    padding: findSize(12),
    paddingBottom: 0,
    elevation: 5,
    width: findSize(105),
    height: findSize(60),
    marginVertical: 5,
  },
});
