import { StyleSheet } from 'react-native';
import {
  POP_MEDIUM,
  ROBO_BOLD,
  ROBO_MEDIUM,
  ROBO_REGULAR,
} from '../../../constants/Fonts';
import { Colors } from '../../../constants/Colors';
import { DEV_HEIGHT, DEV_WIDTH } from '../../../constants/DeviceDetails';

export const styles = StyleSheet.create({
  home: {
    color: Colors.WHITE_COLOR,
    fontSize: 21,
    textAlign: 'left',
    fontFamily: POP_MEDIUM,
    marginBottom: 15,
    marginTop: 40,
  },
  errorModalView: {
    backgroundColor: Colors.WHITE_COLOR,
    height: DEV_HEIGHT / 3,
    width: 'auto',
    paddingVertical: 10,
    borderRadius: 10,
  },
  webView: {
    height: DEV_HEIGHT * 0.3,
    width: DEV_WIDTH - 70,
    backgroundColor: Colors.BG_LIGHT,
    alignSelf: 'center',
    // flex: 1,
    margin: 10,
  },
  skyBg: {
    backgroundColor: Colors.INDIGO_COLOR,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
  },
  skyBoxTitle: {
    fontSize: 25,
    fontFamily: ROBO_MEDIUM,
    color: Colors.WHITE_COLOR,
    textAlign: 'center',
    padding: 20,
  },
  greyBg: {
    backgroundColor: Colors.BG_LIGHT,
    padding: 15,
    justifyContent: 'center',
    marginBottom: 20,
  },
  head: {
    height: 45,
    backgroundColor: Colors.BG_COLOR,
  },
  text: {
    margin: 12,
    color: Colors.WHITE_COLOR,
    fontFamily: ROBO_REGULAR,
    fontSize: 16,
  },
  iconsBtn: {
    width: 45,
    borderRadius: 2,
    padding: 5,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: Colors.SKY_COLOR,
    alignSelf: 'center',
  },
  addIconBtn: {
    height: 40,
    width: 50,
    marginTop: -5,
  },
  row: {
    flexDirection: 'row',
    backgroundColor: Colors.BG_COLOR,
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  exerGrpChev: {
    color: Colors.WHITE_COLOR,
    fontFamily: ROBO_REGULAR,
    marginLeft: 15,
    fontSize: 16,
  },
  exerGroupInput: {
    height: 40,
    width: 120,
    alignSelf: 'center',
    marginBottom: 0,
  },
  exerGrpChecvBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  heads: {
    fontSize: 15,
    color: Colors.WHITE_COLOR,
    fontFamily: ROBO_REGULAR,
    marginBottom: 5,
  },
  inputs: {
    marginBottom: 15,
    height: 40,
  },
  searchBtn: {
    width: 100,
    alignSelf: 'center',
    backgroundColor: Colors.BG_COLOR,
    marginBottom: 25,
    borderWidth: 1,
    borderColor: Colors.SKY_COLOR,
    height: 40,
  },
  userResultBg: {
    backgroundColor: Colors.BG_LIGHT,
    padding: 15,
    borderRadius: 5,
    marginVertical: 7,
  },
  userDetailsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  userResultTxt: {
    color: Colors.WHITE_COLOR,
    fontFamily: ROBO_REGULAR,
    fontSize: 16,
    width: 100,
  },
  resetPassBtn: {
    backgroundColor: Colors.BG_LIGHT,
    borderWidth: 1,
    borderColor: Colors.SKY_COLOR,
    padding: 7,
    borderRadius: 3,
  },
  deleteUserBtn: {
    backgroundColor: Colors.LIGHT_RED,
    borderWidth: 1,
    borderColor: Colors.LIGHT_RED,
    padding: 7,
    borderRadius: 3,
  },
  btnTxt: {
    color: Colors.WHITE_COLOR,
    fontFamily: ROBO_REGULAR,
    fontSize: 16,
  },
  btnRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  exrGrpTxt: {
    fontSize: 16,
    color: Colors.WHITE_COLOR,
    fontFamily: ROBO_REGULAR,
    marginBottom: 5,
  },
  addGroupInput: {
    marginTop: -5,
    width: DEV_WIDTH / 1.5,
    height: 40,
    marginBottom: 0,
  },
  addNewGrpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  groupInputs: {
    marginBottom: 0,
    height: 40,
    width: 175,
  },
  groupLabels: {
    color: Colors.WHITE_COLOR,
    fontFamily: ROBO_REGULAR,
    fontSize: 14,
    width: 90,
  },
  groupRows: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 7,
    justifyContent: 'space-evenly',
  },
  line: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.WHITE_COLOR,
    marginVertical: 10,
  },
  exerciseName: {
    fontSize: 16,
    color: Colors.WHITE_COLOR,
    fontFamily: ROBO_MEDIUM,
    marginLeft: 10,
    width: DEV_WIDTH / 1.2,
    textAlign: 'justify',
  },
  smallPicker: {
    width: 175,
    height: 40,
    marginBottom: 0,
  },
  emptyBox: {
    height: 25,
    width: 25,
    borderWidth: 1.3,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
